In [11]:
import numpy as np
a = np.array([[1, 2, 4], [5, 8, 7]])
print ("Array created using passed list:\n", a)

Array created using passed list:
 [[1 2 4]
 [5 8 7]]


In [12]:
# Creating a 3X4 array with all zeros
b = np.zeros((3, 4))
print ("\nAn array initialized with all zeros:\n", b)


An array initialized with all zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [13]:
#Create a constant value array of complex type
c = np.full((3, 3), 6)
print ("\nAn array initialized with all 6s.\n", c)


An array initialized with all 6s.
 [[6 6 6]
 [6 6 6]
 [6 6 6]]


In [14]:
#Create an array with random values
d = np.random.random((2, 2))
print ("\nA random array:\n", d)


A random array:
 [[0.02503222 0.89524143]
 [0.24807969 0.86192613]]


In [15]:
# Create a sequence of integers from 0 to 30 with steps of 5
e = np.arange(0, 30, 5)
print ("\n A sequential array with steps of 5:\n", e)


 A sequential array with steps of 5:
 [ 0  5 10 15 20 25]


In [17]:
#Reshaping 3X4 array to 2X2X3 array
arr = np.array([[1, 2, 3, 4], [5, 2, 4, 2],[1, 2, 0, 1]])
newarr = arr.reshape(4, 3)
print ("\nOriginal array:\n", arr)
print ("Reshaped array[4,3]:\n", newarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Reshaped array[4,3]:
 [[1 2 3]
 [4 5 2]
 [4 2 1]
 [2 0 1]]


In [18]:
#Flatten array
flarr= arr.flatten()
print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
Fattened array:
 [1 2 3 4 5 2 4 2 1 2 0 1]


In [19]:
# Printing array dimensions (axes)
print("\nNo. of dimensions: ", arr.ndim)


No. of dimensions:  2


In [20]:
# Printing shape of array
print("\nShape of array: ", arr.shape)


Shape of array:  (3, 4)


In [21]:
# Printing size (total number of elements) of array
print("\nSize of array: ", arr.size)


Size of array:  12


In [22]:
# Printing type of elements in array
print("\nArray stores elements of type: ", arr.dtype)


Array stores elements of type:  int32


In [26]:
#converting datatypes from integer to float
newtype=arr.astype('f')
print("\nConverted array elemnets:\n",newtype)



Converted array elemnets:
 [[1. 2. 3. 4.]
 [5. 2. 4. 2.]
 [1. 2. 0. 1.]]


In [27]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:0:-1])

[[10 11 12]
 [ 7  8  9]
 [ 4  5  6]]


In [28]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2,0:2])

[7 8]


In [29]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[2:,2:])

[[ 9]
 [12]
 [15]]


In [30]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[3:,3:])

[]


In [31]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(p[:,1])

[ 2  5  8 11 14]


In [32]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('f')
print(c)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]
 [13. 14. 15.]]


In [33]:
import numpy as np
p=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
c=p.astype('i')
print(c)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
